/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tr_cohort_tv_remote_steps;

import org.junit.Test;
import tr_cohort_job_matching.KeyboardStepsApp;

import static org.junit.Assert.*;

public class KeyboardStepsAppTest {

    @Test
    public void testAppReturnsExpectedStepCountForWordCode() {
        final KeyboardStepsApp classUnderTest = new KeyboardStepsApp();
        assertEquals("should return expected step count", 14, classUnderTest.getStepsToGetWordMatch("code"));
    }

    @Test
    public void testAppReturnsExpectedStepCountForWordC() {
        final KeyboardStepsApp classUnderTest = new KeyboardStepsApp();
        assertEquals("should return expected step count", 3, classUnderTest.getStepsToGetWordMatch("c"));
    }

    @Test
    public void testAppReturnsExpectedStepCountForBlankWord() {
        final KeyboardStepsApp classUnderTest = new KeyboardStepsApp();
        assertEquals("should return expected step count", KeyboardStepsApp.RET_NOT_FOUND, classUnderTest.getStepsToGetWordMatch(""));
    }

    @Test
    public void testAppReturnsNoMatchForInvalidChars() {
        final KeyboardStepsApp classUnderTest = new KeyboardStepsApp();
        assertEquals("should return expected step count", KeyboardStepsApp.RET_NOT_FOUND, classUnderTest.getStepsToGetWordMatch("abc[]+=*&"));
    }
}
